#!/bin/bash

# Shopware Cache Clear Script
# This is a template file. The actual script will be generated by setup.sh
# with the correct PHP path and Shopware version-specific command.

# Change to the Shopware directory
cd "${SHOPWARE_PATH}"

echo "Starting cache clearing at $(date)"

# The PHP path and command will be dynamically set based on user input
${PHP_PATH} bin/console ${CACHE_CLEAR_COMMAND}

RESULT=$?
if [ $RESULT -eq 0 ]; then
    echo "Cache Clear completed successfully."
else
    echo "Error: Cache Clear failed with exit code $RESULT"
fi

echo "Cache Clear completed at $(date)"
